// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMlVdFKaggv45XaNoavrKFIyRKZTR9P0',
    appId: '1:537770747872:web:a857a2e13ddb41cb876d85',
    messagingSenderId: '537770747872',
    projectId: 'inventory-management-a1097',
    authDomain: 'inventory-management-a1097.firebaseapp.com',
    storageBucket: 'inventory-management-a1097.firebasestorage.app',
    measurementId: 'G-QJ5D7CFV2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WGk48EDKZdydxhl8lMhGHtNCr3LEUfU',
    appId: '1:537770747872:android:d29f30ed37eac954876d85',
    messagingSenderId: '537770747872',
    projectId: 'inventory-management-a1097',
    storageBucket: 'inventory-management-a1097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldO08gXfMkPfO61FnuU17qwsRPG1oAVg',
    appId: '1:537770747872:ios:1a0e3a8b7bd3f5ca876d85',
    messagingSenderId: '537770747872',
    projectId: 'inventory-management-a1097',
    storageBucket: 'inventory-management-a1097.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAldO08gXfMkPfO61FnuU17qwsRPG1oAVg',
    appId: '1:537770747872:ios:1a0e3a8b7bd3f5ca876d85',
    messagingSenderId: '537770747872',
    projectId: 'inventory-management-a1097',
    storageBucket: 'inventory-management-a1097.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOMlVdFKaggv45XaNoavrKFIyRKZTR9P0',
    appId: '1:537770747872:web:9a464d2f89d4082e876d85',
    messagingSenderId: '537770747872',
    projectId: 'inventory-management-a1097',
    authDomain: 'inventory-management-a1097.firebaseapp.com',
    storageBucket: 'inventory-management-a1097.firebasestorage.app',
    measurementId: 'G-YFD8TPZLF3',
  );
}
